#!/bin/sh

echo "Running pre-commit checks..."

echo "Running Prettier..."
npm run lint:prettier:fix

if [ $? -ne 0 ]; then
  echo "Prettier failed. Aborting commit."
  exit 1
fi

echo "Running ESLint..."
npm run lint:eslint:fix

if [ $? -ne 0 ]; then
  echo "ESLint failed. Aborting commit."
  exit 1
fi

echo "Pre-commit checks passed. Proceeding with commit."
